#!/usr/bin/env bash
jhead=../jhead

rm -rf results-txt/*
rm -rf results-bin/*
rm -rf *.jpg *.png *.webp
mkdir -p results-txt
mkdir -p results-bin

#test parsing of normal exif information.
for file in normal-digicams/*.jpg; do
  "$jhead" -v -nofdate "$file" > results-txt/${file##*/}
done

#test parsing and display of some strange jpeg files.
for file in strange-jpegs/*.jpg; do
  "$jhead" -v -nofdate "$file" > results-txt/${file##*/}
done

#-------------------------------------------------------------------
#test compact view
echo "Normal digicams" > results-txt/compact-txt
"$jhead" -c normal-digicams/*.jpg >> results-txt/compact-txt
echo "Strange jpegs" >> results-txt/compact-txt
"$jhead" -c strange-jpegs/*.jpg >> results-txt/compact-txt

#-------------------------------------------------------------------
#test date manipulation
cp normal-digicams/3dmsc.jpg time.jpg
"$jhead" -ta+2:00 time.jpg
"$jhead" -ft time.jpg
"$jhead" time.jpg > results-txt/time.txt
"$jhead" -ta-0:00:20 time.jpg
"$jhead" -nofdate time.jpg >> results-txt/time.txt
"$jhead" -da+2005:05:01/01:01-2004:05:01 time.jpg
"$jhead" -nofdate time.jpg >> results-txt/time.txt
cp strange-jpegs/badyear.jpg badyear.jpg
"$jhead" -nofdate badyear.jpg >> results-txt/time.txt
"$jhead" -ds2006:01 -ta+1:00 badyear.jpg >> results-txt/time.txt
"$jhead" -nofdate badyear.jpg >> results-txt/time.txt
cp strange-jpegs/short_date.jpg short_date.jpg
"$jhead" -ta+1:02:03 short_date.jpg
"$jhead" -nofdate short_date.jpg >> results-txt/time.txt

cp strange-jpegs/verizon.jpg verizon.jpg
"$jhead" -ta+0:0:1 verizon.jpg
"$jhead" -nofdate verizon.jpg >> results-txt/time.txt

#-------------------------------------------------------------------
#test comment manipulation
cp normal-digicams/S100.jpg comments.jpg
#insert a comment (-ci)
"$jhead" -ci normal-digicams/testfile.txt -ft comments.jpg
#Show the comments
"$jhead" -nofdate comments.jpg >> results-txt/comments.txt

cp comments.jpg results-bin
#replace comment with a literal comment
"$jhead" -cl "a literal inserted comment!" -ft comments.jpg
"$jhead" -nofdate comments.jpg >> results-txt/comments.txt

#remove the comment again (-dc)
"$jhead" -dc -ft comments.jpg
"$jhead" -nofdate comments.jpg >> results-txt/comments.txt


#-------------------------------------------------------------------
#test rotate command stuff
cp normal-digicams/rotate.jpg results-bin
"$jhead" -norot -ft results-bin/rotate.jpg
"$jhead" results-bin/rotate.jpg > results-txt/rotate.txt
cp normal-digicams/rotate*.jpg results-bin
"$jhead" -autorot -ft results-bin/rotate*.jpg
"$jhead" -nofdate results-bin/rotate*.jpg >> results-txt/rotate.txt

#test with two orientation tags.
cp normal-digicams/two-orientation.jpg results-bin
"$jhead" -autorot results-bin/two-orientation.jpg
"$jhead" -nofdate -v results-bin/two-orientation.jpg >> results-txt/rotate.txt

#test saving of incorrectly placed thumbnail
"$jhead" -st results-bin/thumbnail-place-error.thm strange-jpegs/thumbnail-place-error.jpg

#-------------------------------------------------------------------
#test rename command.
rm -rf temp
mkdir temp
cp normal-digicams/*.jpg temp
rm temp/no-exif.jpg
"$jhead" -nf%02i-%H-%f temp/*.jpg
ls temp > results-txt/new-names-txt

#-------------------------------------------------------------------
#test file move / rename feature
rm -rf movetest
mkdir -p movetest
cp normal-digicams/*.jpg movetest

echo "---Test move/rename abs rel path ---" >> results-txt/new-names-txt
"$jhead" -nf./movetest/%Y/%f- -de movetest/*.jpg
"$jhead" -c movetest/*/*.jpg >> results-txt/new-names-txt


echo "---Test move/rename relative path ---" >> results-txt/new-names-txt
"$jhead" -nf%i/%f movetest/2004/d*g
"$jhead" -c movetest/2004/?/*.jpg >> results-txt/new-names-txt

#-------------------------------------------------------------------
#test -purejpg with an image that I used to corrupt.
cp strange-jpegs/olav.jpg results-bin
"$jhead" -purejpg results-bin/olav.jpg
"$jhead" -v -nofdate results-bin/olav.jpg > results-txt/olav.jpg

#test -purejpg with an image wth multiple copies of the same type of section
cp strange-jpegs/don.jpg results-bin
"$jhead" -purejpg results-bin/don.jpg
"$jhead" -v -nofdate results-bin/don.jpg > results-txt/don.jpg

#-------------------------------------------------------------------
#Test deletion of a thumbnail, and replacing of a thumbnail
rm results-txt/thumb-operations-txt

cp normal-digicams/fuji-dx10.jpg results-bin/thumb-deleted.jpg
"$jhead" -dt -ft results-bin/thumb-deleted.jpg
cp results-bin/thumb-deleted.jpg results-bin/thumb-inserted.jpg

#reinsert a different thumbnail
"$jhead" -rt normal-digicams/no-exif.jpg results-bin/thumb-inserted.jpg

#replace thumbnail in one step
cp normal-digicams/olympus.jpg results-bin/thumb-replaced.jpg
"$jhead" -rt normal-digicams/no-exif.jpg results-bin/thumb-replaced.jpg

#try manipulating a header with no thumbnail pointers.
cp strange-jpegs/no-thumb-pointer.jpg results-bin
echo "Trying to remove nonexistent:" >> results-txt/thumb-operations-txt
"$jhead" -dt results-bin/no-thumb-pointer.jpg >> results-txt/thumb-operations-txt
"$jhead" -v -nofdate res*bin/no-thumb-pointer.jpg >> results-txt/thumb-operations-txt
echo "Trying to replace with no pointers:" >> results-txt/thumb-operations-txt
"$jhead" -rtt results-bin/no-thumb-pointer.jpg >> results-txt/thumb-operations-txt

"$jhead" -v -nofdate res*bin/*thumb-*.jpg >> results-txt/thumb-operations-txt

#-------------------------------------------------------------------
#Test generating a thumbnail
cp normal-digicams/fuji-dx10.jpg results-bin/exif-regen.jpg
"$jhead" -mkexif results-bin/exif-regen.jpg
#Test regenerating using old exif date
"$jhead" -v -nofdate results-bin/exif-regen.jpg > results-txt/exif-regen-txt
"$jhead" -ft -de results-bin/exif-regen.jpg
#Test regenerating using file time for timestamp.  also create thumbnail.
"$jhead" -mkexif -rgt results-bin/exif-regen.jpg
"$jhead" -v -nofdate results-bin/exif-regen.jpg >> results-txt/exif-regen-txt

#-------------------------------------------------------------------
#Test exif header zero trimming
cp normal-digicams/35mmequiv-tag.jpg results-bin/ztrim1.jpg
cp normal-digicams/two-orientation.jpg results-bin/ztrim240.jpg
cp normal-digicams/sony.jpg results-bin/ztrim0.jpg
echo "---------run zerotrim" >> results-txt/zerotrim-txt
"$jhead" -zt -nofdate results-bin/ztrim*.jpg >> results-txt/zerotrim-txt
echo "---------run zerotrim again" >> results-txt/zerotrim-txt
"$jhead" -zt -nofdate results-bin/ztrim*.jpg >> results-txt/zerotrim-txt
echo "---------jehad -v on trimmed files" >> results-txt/zerotrim-txt
"$jhead" -v -nofdate results-bin/ztrim?.jpg >> results-txt/zerotrim-txt

#-------------------------------------------------------------------
#Test IPTC manipulation
cp strange-jpegs/iptc?.jpg results-bin/
"$jhead" -di results-bin/iptc1.jpg
#test removal and restoration of iptc section
"$jhead" -de results-bin/iptc2.jpg
"$jhead" -nofdate results-bin/iptc?.jpg > results-txt/iptc-txt

#test XMP non-delete
cp strange-jpegs/with_xmp.jpg results-bin/
"$jhead" -ta+1:00 results-bin/with_xmp.jpg > results-txt/with_xmp.jpg
"$jhead" -v -nofdate results-bin/with_xmp.jpg >> results-txt/with_xmp.jpg
"$jhead" -purejpg results-bin/with_xmp.jpg >> results-txt/with_xmp.jpg
"$jhead" -v -nofdate results-bin/with_xmp.jpg >> results-txt/with_xmp.jpg
cp strange-jpegs/with_xmp.jpg results-bin/keep_xmp.jpg
"$jhead" -dx results-bin/keep_xmp.jpg
"$jhead" -v -nofdate results-bin/keep_xmp.jpg >> results-txt/with_xmp.jpg


#-------------------------------------------------------------------
#Test PNG file handling
echo "--------Normal view:" >> results-txt/pngfiles-txt
"$jhead" -nofdate pngfiles/*.png >> results-txt/pngfiles-txt
echo "--------Compact view:" >> results-txt/pngfiles-txt
"$jhead" -nofdate -c pngfiles/*.png >> results-txt/pngfiles-txt
echo "--------Verbose view:" &>> results-txt/pngfiles-txt
"$jhead" -nofdate -v pngfiles/*.png >> results-txt/pngfiles-txt

echo "--------Bad crc:" &>> results-txt/pngfiles-txt
"$jhead" -nofdate -v pngfiles/bad_crc.png_x >> results-txt/pngfiles-txt 2>>results-txt/pngfiles-txt

echo "--------Comment replace:" >> results-txt/pngfiles-txt
cp pngfiles/ctest.png results-bin/
"$jhead" -cl "A brand n./runew comment!" results-bin/ctest.png >> results-txt/pngfiles-txt
"$jhead" -nofdate results-bin/ctest.png >> results-txt/pngfiles-txt

echo "--------Deleted comment:" >> results-txt/pngfiles-txt
"$jhead" -dc results-bin/ctest.png >> results-txt/pngfiles-txt
"$jhead" -nofdate results-bin/ctest.png >> results-txt/pngfiles-txt

echo "--------Zero trim png exif header and set file time:" >> results-txt/pngfiles-txt
cp pngfiles/from_photo.png results-bin/from_photo.png
"$jhead" -zt -ft results-bin/from_photo.png >> results-txt/pngfiles-txt
"$jhead" -v results-bin/from_photo.png >> results-txt/pngfiles-txt
echo "--------Replace with minimal exif header:" >> results-txt/pngfiles-txt
"$jhead" -mkexif results-bin/from_photo.png >> results-txt/pngfiles-txt
"$jhead" -nofdate results-bin/from_photo.png >> results-txt/pngfiles-txt

echo "--------Remove exif header:" >> results-txt/pngfiles-txt
"$jhead" -de -v results-bin/from_photo.png >> results-txt/pngfiles-txt
echo "--------Resulting file:" >> results-txt/pngfiles-txt
"$jhead" -nofdate results-bin/from_photo.png >> results-txt/pngfiles-txt
echo "--------REsulting file verbose:" >> results-txt/pngfiles-txt
# Specify time adjust to make it read all of exif file (so it prints the tags in verbose mode)
"$jhead" -v -nofdate -ta+0:0:1 results-bin/from_photo.png >> results-txt/pngfiles-txt

echo "--------PNG date manipulation:" >> results-txt/pngfiles-txt
cp pngfiles/from_photo.png nametest.png
"$jhead" -ts2026:02:24-22:00:00 nametest.png >> results-txt/pngfiles-txt
"$jhead" -ta+00:23:24 nametest.png >> results-txt/pngfiles-txt
"$jhead" -nnametest-%Y%m%dt-%H%M%S nametest.png >> results-txt/pngfiles-txt
"$jhead" -c nametest*.png >> results-txt/pngfiles-txt

echo "--------PNG metadata removal:" >> results-txt/pngfiles-txt
cp pngfiles/*.png .
"$jhead" -pure *.png >> results-txt/pngfiles-txt
"$jhead" -nofdate -v *.png >> results-txt/pngfiles-txt


#-------------------------------------------------------------------
#Test weebp file handling

echo "--------Show webp contents------" >> results-txt/webpfiles-txt
"$jhead" -nofdate webpfiles/*.webp >> results-txt/webpfiles-txt
echo "--------Show webp contents verbose------" >> results-txt/webpfiles-txt
"$jhead" -nofdate -v webpfiles/*.webp >> results-txt/webpfiles-txt
cp webpfiles/basic.webp basic.webp
echo "--------Add exif header to basic webp------" >> results-txt/webpfiles-txt
"$jhead" -mkexif -ts2026:03:25-19:30:45 -ft basic.webp >> results-txt/webpfiles-txt
echo "--------Shopw header ------" >> results-txt/webpfiles-txt
"$jhead" -v basic.webp >> results-txt/webpfiles-txt
# Should also create a thumbnail here but that's not working this moment.

"$jhead" -n basic.webp >> results-txt/webpfiles-txt
echo "--------Remove exif header ------" >> results-txt/webpfiles-txt
"$jhead" -de 0325*.webp >> results-txt/webpfiles-txt
"$jhead" -nofdate -v 0325*.webp >> results-txt/webpfiles-txt


cp webpfiles/from_iphone.webp .
echo "--------Remove XMP from from_iphone.webp header ------" >> results-txt/webpfiles-txt
"$jhead" -dx from_iphone.webp >> results-txt/webpfiles-txt
"$jhead" -nofdate -v from_iphone.webp >> results-txt/webpfiles-txt
echo "--------Adjust timestamp and set file date ------" >> results-txt/webpfiles-txt
"$jhead" -ta+01:02:03 from_iphone.webp >> results-txt/webpfiles-txt
"$jhead" -ft from_iphone.webp >> results-txt/webpfiles-txt
"$jhead" -nofdate from_iphone.webp >> results-txt/webpfiles-txt
echo "--------Remove exif header ------" >> results-txt/webpfiles-txt
"$jhead" -de from_iphone.webp >> results-txt/webpfiles-txt
"$jhead" -v -nofdate from_iphone.webp >> results-txt/webpfiles-txt
echo "--------Re-add exif header ------" >> results-txt/webpfiles-txt
"$jhead" -mkexif from_iphone.webp >> results-txt/webpfiles-txt
"$jhead" -v -nofdate from_iphone.webp >> results-txt/webpfiles-txt

# Test to make sure sections are padded to even length
cp webpfiles/basic.webp commentlen.webp
echo "--------Even length comment-----" >> results-txt/webpfiles-txt
"$jhead" -cl "even length stays!" commentlen.webp >> results-txt/webpfiles-txt
"$jhead" -v -nofdate commentlen.webp >> results-txt/webpfiles-txt
echo "--------Odd length comment-----" >> results-txt/webpfiles-txt
"$jhead" -cl "odd size rounds up!" commentlen.webp >> results-txt/webpfiles-txt
"$jhead" -v -nofdate commentlen.webp >> results-txt/webpfiles-txt

# Test webp metadata removal
echo "--------Metadata deletion-----" >> results-txt/webpfiles-txt
cp webpfiles/from_iphone.webp .
"$jhead" -pure from_iphone.webp commentlen.webp >> results-txt/webpfiles-txt
"$jhead" -v -nofdate from_iphone.webp commentlen.webp >> results-txt/webpfiles-txt

# Test webp clear rotation
echo "--------Webpfile clear rotation tag-----" >> results-txt/webpfiles-txt
cp webpfiles/clearrot.webp .
"$jhead" -norot clearrot.webp >> results-txt/webpfiles-txt
"$jhead" -v -nofdate clearrot.webp >> results-txt/webpfiles-txt
echo "--------done-----" >> results-txt/webpfiles-txt

# Test thumbnail manipulation of webp files

cp webpfiles/basic.webp basic.webp 
echo "--------Add exif wth thumbnail ----" >> results-txt/wp_thmb-txt
"$jhead" -mkexif -rgt -ts2026:03:25-01:02:03 basic.webp >> results-txt/wp_thmb-txt
"$jhead" -nofdate -v basic.webp >> results-txt/wp_thmb-txt
echo "--------Save the thumbnail ---" >> results-txt/wp_thmb-txt
"$jhead" -st th.webp basic.webp >> results-txt/wp_thmb-txt
echo "--------Examine thumbanil -- dependent on imagemagick version ---" >> results-txt/wp_thmb-txt
"$jhead" -v -nofdate th.webp >> results-txt/wp_thmb-txt
echo "--------Attempt to save without thumbnail ---" >> results-txt/wp_thmb-txt
"$jhead" -dt basic.webp >> results-txt/wp_thmb-txt
"$jhead" -st thx.webp basic.webp >> results-txt/wp_thmb-txt
echo "--------Check that no thumbnail got saved ---" >> results-txt/wp_thmb-txt
"$jhead" thx.webp basic.webp >> results-txt/wp_thmb-txt
echo "--------Make new custom size thumbnail ---" >> results-txt/wp_thmb-txt
"$jhead" -rgt320 basic.webp >> results-txt/wp_thmb-txt
echo "--------and save thumbnail ---" >> results-txt/wp_thmb-txt
"$jhead" -st th320.webp basic.webp >> results-txt/wp_thmb-txt
"$jhead" -v -nofdate th320.webp >> results-txt/wp_thmb-txt

# Test thumbnail manipulation of png files
echo "--------Now test with png ---" >> results-txt/wp_thmb-txt
cp pngfiles/ctest.png ctest.png
"$jhead" -rgt200 ctest.png >> results-txt/wp_thmb-txt
"$jhead" -st th200.png ctest.png >> results-txt/wp_thmb-txt
echo "--------Examine thumbnail.  Very dependent on imagemagick version ---" >> results-txt/wp_thmb-txt
"$jhead" -nofdate th200.png ctest.png >> results-txt/wp_thmb-txt
echo "--------Just for kicks, use webp file for png thumbnail ---" >> results-txt/wp_thmb-txt
"$jhead" -rt basic.webp ctest.png >> results-txt/wp_thmb-txt
"$jhead" -nofdate -v pngfiles/ctest.png >> results-txt/wp_thmb-txt



echo "--------------------------------------------------------------------------"
if diff -qr expected-txt/ results-txt/ ; then
    echo "All tests passed Passed!"
else
    echo "--------------------------------------------------------------------------"
    echo "Tests Failed - see differences above."
fi